export const ADD_QUESTION = 'ADD_QUESTION';
export const GET_QUESTION = 'GET_QUESTION';
export const DELETE_QUESTION = 'DELETE_QUESTION';
export const UPDATE_QUESTION = 'UPDATE_QUESTION';
export const CLEAR_CURRENT_QUESTION = 'CLEAR_CURRENT_QUESTION';
export const SET_CURRENT_QUESTION = 'SET_CURRENT_QUESTION';
export const CLEAR_FORM = 'CLEAR_FORM';
export const CURRENT_FORM_NAME = 'CURRENT_FORM_NAME';
export const SET_UPDATE_FORM_QUESTIONS = 'SET_UPDATE_FORM_QUESTIONS';

export const CREATE_FORM_REQESTED = 'CREATE_FORM_REQESTED';
export const CREATE_FORM_SUCCEEDED = 'CREATE_FORM_SUCCEEDED';
export const CREATE_FORM_FAILED = 'CREATE_FORM_FAILED';

export const GET_FORMS_REQUESTED = 'GET_FORMS_REQUESTED';
export const GET_FORMS_SUCCEEDED = 'GET_FORMS_SUCCEEDED';
export const GET_FORMS_FAILED = 'GET_FORMS_FAILED';

export const UPDATE_FORM_REQUESTED = 'UPDATE_FORM_REQUESTED';
export const UPDATE_FORM_SUCCEEDED = 'UPDATE_FORM_SUCCEEDED';
export const UPDATE_FORM_FAILED = 'UPDATE_FORM_FAILED';

export const DELETE_FORM_REQUESTED = 'DELETE_FORM_REQUESTED';
export const DELETE_FORM_SUCCEEDED = 'DELETE_FORM_SUCCEEDED';
export const DELETE_FORM_FAILED = 'DELETE_FORM_FAILED';

export const SET_CURRENT_FORM_REQUESTED = 'SET_CURRENT_FORM_REQUESTED';
export const SET_CURRENT_FORM_SUCCEEDED = 'SET_CURRENT_FORM_SUCCEEDED';
export const SET_CURRENT_FORM_FAILED = 'SET_CURRENT_FORM_FAILED';

export const CLEAR_CURRENT_FORM = 'CLEAR_CURRENT_FORM';

export const SUBMIT_FORM_RESPONSES = 'SUBMIT_FORM_RESPONSES';
