export const ADD_QUESTION = 'ADD_QUESTION';
export const GET_QUESTION = 'GET_QUESTION';
export const DELETE_QUESTION = 'DELETE_QUESTION';
export const UPDATE_QUESTION = 'UPDATE_QUESTION';
export const CLEAR_CURRENT_QUESTION = 'CLEAR_CURRENT_QUESTION';
export const SET_CURRENT_QUESTION = 'SET_CURRENT_QUESTION';
export const CLEAR_FORM = 'CLEAR_FORM';

export const CREATE_FORM = 'CREATE_FORM';
export const SET_CURRENT_FORM = 'SET_CURRENT_FORM';
export const CURRENT_FORM_NAME = 'CURRENT_FORM_NAME';

export const SUBMIT_FORM_RESPONSES = 'SUBMIT_FORM_RESPONSES';
